# Generated by Django 3.1.13 on 2021-12-02 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='image/hoso/%Y/%m')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hoso.category')),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('title', 'category')},
            },
        ),
        migrations.CreateModel(
            name='NopHoSo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='image/hoso/%Y/%m')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('fullname', models.TextField(blank=True, null=True)),
                ('cmnd', models.TextField(blank=True, null=True)),
                ('ngaythangnamsinh', models.CharField(blank=True, max_length=10, null=True)),
                ('sonha', models.TextField(blank=True, null=True)),
                ('tonha', models.TextField(blank=True, null=True)),
                ('huyennha', models.TextField(blank=True, null=True)),
                ('tinhnha', models.TextField(blank=True, null=True)),
                ('sdt', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('hoso', models.FileField(blank=True, default=None, null=True, upload_to='file/hoso/%Y/%m')),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vanban', to='hoso.category')),
                ('field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vanban', to='hoso.field')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('title', 'field')},
            },
        ),
        migrations.CreateModel(
            name='StatusHoSo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Đang chờ'), (1, 'Đã xem'), (2, 'Thành công'), (3, 'Thất bại')], default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('hosonop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hoso.nophoso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FileHoSo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='image/hoso/%Y/%m')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('hoso', models.FileField(blank=True, default=None, null=True, upload_to='file/hoso/%Y/%m')),
                ('description', models.TextField(blank=True, null=True)),
                ('field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='hoso.field')),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('title', 'field')},
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hoso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoso.filehoso')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'none'), (1, 'check'), (2, 'fail')], default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hoso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoso.filehoso')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
