# Generated by Django 3.1.13 on 2021-12-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoso', '0002_cauhoi_cauhoipublic'),
    ]

    operations = [
        migrations.AddField(
            model_name='nophoso',
            name='hosoduocky',
            field=models.FileField(blank=True, default=None, null=True, upload_to='file/hosoky/%Y/%m'),
        ),
    ]
