# Generated by Django 3.1.13 on 2021-12-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoso', '0003_nophoso_hosoduocky'),
    ]

    operations = [
        migrations.AddField(
            model_name='nophoso',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Đang chờ'), (1, 'Đã xem'), (2, 'Thành công'), (3, 'Thất bại')], default=0),
        ),
    ]
